privatezone接入
alibaba/terraform-provider pull request #604
Opened 2018-08-15 15:34 UTC by forcoder

pvtz

fix bugs

bugfix

bugfix

bugfix

bugfix

2018-08-15 15:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/terraform-provider?pullRequest=604) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/terraform-provider?pullRequest=604) before we can accept your contribution.<br/><hr/>**qiaozhou** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/terraform-provider?pullRequest=604) it.</sub>

2018-08-15 15:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/terraform-provider?pullRequest=604) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/terraform-provider?pullRequest=604) before we can accept your contribution.<br/><hr/>**qiaozhou** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/terraform-provider?pullRequest=604) it.</sub>

2018-08-16 07:21 UTC, xiaozhu36 requested changes

2018-08-16 07:29 UTC, forcoder commented on alicloud/data_source_alicloud_pvtz_zone.go
> +						},
zone_id之类不用和openapi的统一对齐吗？

2018-08-16 07:30 UTC, forcoder commented on alicloud/data_source_alicloud_pvtz_zone.go
> +						"update_timestamp": {
这个不用和openapi返回结果对齐是吧？

2018-08-16 07:32 UTC, forcoder commented on alicloud/errors.go
> +			strings.Contains(strings.ToLower(e.Message()), MessageInstanceNotFound) || e.ErrorCode() == ZoneNotExists) {
你指的是用IsExceptedError()这个方法？

2018-08-16 07:34 UTC, forcoder commented on alicloud/resource_alicloud_pvtz_zone_record.go
> +				Required: true,
https://help.aliyun.com/document_detail/66251.html?spm=a2c4g.11186623.6.579.vUaSUV

2018-08-16 07:34 UTC, forcoder commented on alicloud/resource_alicloud_pvtz_zone_record.go
> +				Required: true,
![image](https://user-images.githubusercontent.com/5011087/44194861-dca15a00-a169-11e8-80e9-28dfa831cbaf.png)

2018-08-16 07:35 UTC, forcoder commented on alicloud/resource_alicloud_pvtz_zone_record.go
> +	return parts[0], parts[1], parts[2], nil
因为我有场景不是直接使用getRecordIdAndZoneIdAndRr，而是需要使用splitRecordIdAndZoneIdAndRr，所以拆分成两个方法

2018-08-16 07:36 UTC, forcoder commented on alicloud/service_alicloud_pvtz.go
> +	}
能给个具体的参考产品？

2018-08-16 07:40 UTC, xiaozhu36 commented on alicloud/errors.go
> +			strings.Contains(strings.ToLower(e.Message()), MessageInstanceNotFound) || e.ErrorCode() == ZoneNotExists) {
是的

2018-08-16 07:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_pvtz_zone_record.go
> +				Required: true,
我明白，但terraform设计理念是通常不管理资源声明周期内的状态

2018-08-16 07:44 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_pvtz_zone.go
> +			"pvtz_zones": &schema.Schema{
不会混淆的，用户在引用是是通过data.alicloud_pvtz_zones.xxx.zones.0.id来引用的

2018-08-16 07:45 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_pvtz_zone.go
> +			"pvtz_zones": &schema.Schema{
另外，文件data source的文件名应该改为data_source_alicloud_pvtz_zones.go

2018-08-16 07:46 UTC, xiaozhu36 commented on alicloud/data_source_alicloud_pvtz_zone.go
> +						},
不需要，如果要和API对其，就没发看了，现在咱们的API都存在很多不规范，现在我所在的团队正太规范化。另外，terraform内部保证对其就好了

2018-08-16 07:47 UTC, xiaozhu36 commented on alicloud/service_alicloud_pvtz.go
> +	}
任何一个都行，比如vpc

2018-08-16 09:27 UTC, forcoder commented on alicloud/resource_alicloud_pvtz_zone_record.go
> +	request.Keyword = rr
recordId就可以直接确认一个record，但是他没有根据recordId查询record详情的接口

2018-08-21 16:37 UTC, xiaozhu36 requested changes

2018-08-21 16:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_pvtz_zone.go
> +	d.Partial(false)
115行可以删掉了

2018-08-21 16:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_pvtz_zone_attachment.go
> +				Type:     schema.TypeList,
vpc_ids的类型最好申明为set，否则当vpc_ids内的顺序改变时，该资源会出现diff

2018-08-21 16:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_pvtz_zone_record.go
> +	request.Keyword = rr
这个地方不一定要查询到唯一的一个record，根据zoneId查询到一组record之后，可以根据recordId进行过滤，这样可以省去rr

2018-08-21 16:37 UTC, xiaozhu36 commented on alicloud/resource_alicloud_pvtz_zone.go
> +			if NotFoundError(err) || IsExceptedError(err, ZoneNotExists) {
135行直接判断NotFoundError(err)就够了，因为DescribePvtzZoneInfo中应对IsExceptedError(err, ZoneNotExists)进行了处理

2018-08-21 16:37 UTC, xiaozhu36 commented on website/docs/d/pvtz_zone_records.html.markdown
> +# alicloud\_pvtz_zone_records
第9行修改为：alicloud\_pvtz\_zone\_records
下同

2018-08-21 16:37 UTC, xiaozhu36 commented on website/docs/r/pvtz_zone_record.html.markdown
> +* `record_id` - The ID of the Private Zone Record.
49行我觉得应该是id，不是record_id

2018-08-21 16:37 UTC, xiaozhu36 commented on website/docs/r/pvtz_zone_attachment.html.markdown
> +
出参中有一个id，要说明

2018-08-21 16:37 UTC, xiaozhu36 commented on website/docs/d/pvtz_zone_records.html.markdown
> +* `record_id` - ID of the Private Zone Record.
应该是ID，部署record_id 吧

2018-08-21 16:37 UTC, xiaozhu36 commented on alicloud/validators.go
> +func validatePrivateZoneRecordPriority(v interface{}, k string) (ws []string, errors []error) {
这个函数完全可以用validateIntegerInRange替换掉

2018-08-22 08:58 UTC, xiaozhu36 requested changes

2018-08-22 08:58 UTC, xiaozhu36 commented on alicloud/config.go
> +		endpoints.AddEndpointMapping(c.RegionId, string(PVTZCode), endpoint)
既然 private zone是中心化的产品，那么就加一条逻辑吧：当endpoint为空时，endpoint为：pvtz.aliyuncs.com

2018-08-22 08:58 UTC, xiaozhu36 commented on alicloud/resource_alicloud_pvtz_zone_attachment.go
> +		d.SetId(args.ZoneId)
83行就不用再set id了

2018-08-22 08:58 UTC, xiaozhu36 commented on alicloud/resource_alicloud_pvtz_zone_attachment.go
> +			if NotFoundError(err) || IsExceptedError(err, ZoneNotExists) {
136如果是检查ZoneNotExists，有NotFoundError就够了

2018-08-22 08:58 UTC, xiaozhu36 commented on website/alicloud.erb
>                          <li<%= sidebar_current("docs-alicloud-datasource-ram-users") %>>
vendor的变化也要提交上来

2018-08-22 12:28 UTC, xiaozhu36 approved these changes

2018-08-22 12:28 UTC, merged