support alicloud_ess_lifecycle_hook
alibaba/terraform-provider pull request #605
Opened 2018-08-16 05:28 UTC by TalentNing

* alicloud_ess_scalinggroup support multi_az_policy parameter.
* alicloud_ess_scaling_configuration support password_inherit parameter.
* alicloud_ess_scaling_configuration support spot_strategy and spot_price_limit parameters for spot instance.

=== RUN   TestAccAliCloudEssLifecycleHook_import
--- PASS: TestAccAliCloudEssLifecycleHook_import (7.72s)
=== RUN   TestAccAliCloudEssLifecycleHook_basic
--- PASS: TestAccAliCloudEssLifecycleHook_basic (4.71s)
=== RUN   TestAccAliCloudEssLifecycleHook_update
--- PASS: TestAccAliCloudEssLifecycleHook_update (5.37s)
=== RUN   TestAccAlicloudEssScalingGroup_multi_az_policy
--- PASS: TestAccAlicloudEssScalingGroup_multi_az_policy (5.06s)
=== RUN   TestAccAlicloudEssScalingConfiguration_passwordInherit
--- PASS: TestAccAlicloudEssScalingConfiguration_passwordInherit (15.55s)
=== RUN   TestAccAlicloudEssScalingConfiguration_spot
--- PASS: TestAccAlicloudEssScalingConfiguration_spot (10.53s)

2018-08-16 05:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/terraform-provider?pullRequest=605) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/terraform-provider?pullRequest=605) before we can accept your contribution.<br/><hr/>**kangning.tkn** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/terraform-provider?pullRequest=605) it.</sub>

2018-08-16 05:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/terraform-provider?pullRequest=605) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/terraform-provider?pullRequest=605) before we can accept your contribution.<br/><hr/>**kangning.tkn** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/terraform-provider?pullRequest=605) it.</sub>

2018-08-20 15:43 UTC, xiaozhu36 requested changes

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +			},
lifecycle_transition 有可选值么？

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +			},
heartbeat_timeout有取值范围么

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +			},
action_result有可选值么？
CONTINUE 最好可以声明为一个const

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +	d.Set("action_result", hook.DefaultResult)
这个action_result最好还是改为defaultResult吧

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +
既然update方法中只有一个动作ModifyLifecycleHook，那么有关partial的设置可以去掉了

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +	if timeout := requests.NewInteger(d.Get("heartbeat_timeout").(int)); timeout != "" {
172行，最好写成如下：
```
if timeout, ok :=d.GetOk("heartbeat_timeout"); ok && timeout.(int) > 0 {
         args.HeartbeatTimeout = requests.NewInteger(timeout.(int))
}
```

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +	return args, nil
该方法中既然没有可以出错的地方，返回值就没必要返回nil了

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook_test.go
> +		if _, err := client.DescribeLifecycleHookById(rs.Primary.ID); err != nil {
150行的continue是什么意思

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook_test.go
> +			continue
152行，既然有错，就要处理错误

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook_test.go
> +	removal_policies = ["OldestInstance", "NewestInstance"]
既然有些region已经不支持classic的group了，为了提供测试的成功率，那么测试用例中的group必须都是vpc的

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_scalingconfiguration.go
> +
有关configuration的修改，单独提交一个PR

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_scalinggroup.go
>  				Optional:   true,
有关group的修改，单独提交一个PR

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/service_alicloud_ess.go
> +		err = GetNotFoundErrorFromString(GetNotFoundMessage("Lifecycle Hook", hookId))
27行的err什么时候返回

2018-08-20 15:43 UTC, xiaozhu36 commented on alicloud/service_alicloud_ess.go
> +func (client *AliyunClient) DeleteLifecycleHookById(hookId string) error {
这个方法DeleteLifecycleHookById为什么要单独提出来

2018-08-20 15:43 UTC, xiaozhu36 commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +	removal_policies = ["OldestInstance", "NewestInstance"]
同样修改为vpc类型

2018-08-20 15:43 UTC, xiaozhu36 commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +	notification_arn = "acs:ess:cn-beijing:1619897336813314:queue/test"
最好不要暴露一个有效的accountid

2018-08-20 15:43 UTC, xiaozhu36 commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +* `lifecycle_transition` - (Required) Type of Scaling activity attached to lifecycle hook.Supported value: SCALE_OUT,SCALE_IN.
我理解SCALE_OUT,SCALE_IN中间因该有个空格吧

2018-08-20 15:43 UTC, xiaozhu36 commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +* `name` - (Optional) The name of the lifecycle hook,which is a string containing 2 to 40 English or Chinese characters.If this parameter value is not specified, the default value is lifecycle hook i
Chinese characters.If 中间应该有个空格

2018-08-20 15:43 UTC, xiaozhu36 commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +* `notification_arn` - The arn of notification target.
如果该资源支持import，那就显示说明下

另外，检查下文档，有些地方缺少该有的空格

同时，website/docs/r/ess_scaling_lifecycle_hook.html.markdown 没有在website/alicloud.erb中注册

2018-08-20 17:04 UTC, TalentNing commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +			},
[30, 21600]

2018-08-20 17:04 UTC, TalentNing commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +			},
必传参数，支持以下值：
SCALE_OUT：伸缩组弹性扩张活动
SCALE_IN：伸缩组弹性收缩活动

2018-08-20 17:06 UTC, TalentNing commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +	d.Set("action_result", hook.DefaultResult)
ok

2018-08-20 17:06 UTC, TalentNing commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +
ok

2018-08-20 17:06 UTC, TalentNing commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +	removal_policies = ["OldestInstance", "NewestInstance"]
是指测试资源使用vpc的来做吗？

2018-08-20 17:07 UTC, TalentNing commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +	notification_arn = "acs:ess:cn-beijing:1619897336813314:queue/test"
好的  我会做下数据模糊化

2018-08-20 17:07 UTC, TalentNing commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +* `lifecycle_transition` - (Required) Type of Scaling activity attached to lifecycle hook.Supported value: SCALE_OUT,SCALE_IN.
ok  that seems better

2018-08-20 17:08 UTC, TalentNing commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +* `name` - (Optional) The name of the lifecycle hook,which is a string containing 2 to 40 English or Chinese characters.If this parameter value is not specified, the default value is lifecycle hook i
ok

2018-08-20 17:08 UTC, TalentNing commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +* `notification_arn` - The arn of notification target.
roger that

2018-08-20 17:09 UTC, TalentNing commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +			},
支持：
CONTINUE
ABANDON

2018-08-21 09:18 UTC, TalentNing commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +			},
增加了校验

2018-08-21 09:18 UTC, TalentNing commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +			},
增加了校验

2018-08-21 09:18 UTC, TalentNing commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +			},
增加了校验

2018-08-21 09:36 UTC, TalentNing commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +* `lifecycle_transition` - (Required) Type of Scaling activity attached to lifecycle hook.Supported value: SCALE_OUT,SCALE_IN.
优化了文档

2018-08-21 09:40 UTC, TalentNing commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +* `notification_arn` - The arn of notification target.
注册了

2018-08-21 10:10 UTC, TalentNing commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +	removal_policies = ["OldestInstance", "NewestInstance"]
修改了

2018-08-21 10:26 UTC, TalentNing commented on alicloud/service_alicloud_ess.go
> +		err = GetNotFoundErrorFromString(GetNotFoundMessage("Lifecycle Hook", hookId))
修改了

2018-08-21 16:14 UTC, xiaozhu36 requested changes

2018-08-21 16:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +				Default:      "CONTINUE",
48行default值改成常量Continue

2018-08-21 16:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +	}
没有partial，setpartial也就没用了

2018-08-21 16:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +func buildAlicloudEssLifeCycleHookArgs(d *schema.ResourceData, meta interface{}) (*ess.CreateLifecycleHookRequest) {
返回值如果只有一个，不用括号

2018-08-21 16:14 UTC, xiaozhu36 commented on alicloud/resource_alicloud_ess_lifecyclehook_test.go
> +	availability_zone = "cn-beijing-b"
availability_zone不要写成常量，使用data source引用，否则region改变后，这个test case是不过的

2018-08-21 16:14 UTC, xiaozhu36 commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +* `name` - (Optional) The name of the lifecycle hook,which is a string containing 2 to 40 English or Chinese characters. If this parameter value is not specified, the default value is lifecycle hook
hook,which  中间应该有空行

2018-08-21 16:14 UTC, xiaozhu36 commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +* `heartbeat_timeout` - (Optional) Defines the amount of time, in seconds, that can elapse before the lifecycle hook times out. When the lifecycle hook times out, Auto Scaling performs the action def
value:600 中间应该有空行

2018-08-21 16:14 UTC, xiaozhu36 commented on website/docs/r/ess_scaling_lifecycle_hook.html.markdown
> +* `notification_arn` - The arn of notification target.
继续检查下

2018-08-22 04:12 UTC, TalentNing commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +	}
删除setpartial

2018-08-22 04:12 UTC, TalentNing commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +				Default:      "CONTINUE",
已修改

2018-08-22 04:25 UTC, TalentNing commented on alicloud/resource_alicloud_ess_lifecyclehook.go
> +func buildAlicloudEssLifeCycleHookArgs(d *schema.ResourceData, meta interface{}) (*ess.CreateLifecycleHookRequest) {
删除括号

2018-08-22 09:04 UTC, xiaozhu36 approved these changes

2018-08-22 09:04 UTC, merged